package com.forgeos.agent.domain;

public enum AgentRole {
    PROJECT_MANAGER,
    SCRUM_MASTER,
    BUSINESS_ANALYST,
    PRODUCT_MANAGER,
    SOLUTION_ARCHITECT,
    SOFTWARE_ARCHITECT,
    FRONTEND_ENGINEER,
    BACKEND_ENGINEER,
    DATABASE_ENGINEER,
    QA_ENGINEER,
    TEST_AUTOMATION_ENGINEER,
    DEVOPS_ENGINEER,
    SRE_ENGINEER,
    SECURITY_ENGINEER,
    AI_ML_ENGINEER,
    TECHNICAL_WRITER,
    CODE_REVIEWER,
    COST_OPTIMIZATION_ENGINEER,
    UX_UI_ENGINEER,
    RELEASE_ENGINEER
}
