package com.forgeos.agent.domain;

public enum AgentCapability {
    REQUIREMENTS_ANALYSIS,
    ARCHITECTURE_DESIGN,
    CODE_GENERATION,
    CODE_MODIFICATION,
    CODE_REVIEW,
    DATABASE_DESIGN,
    TEST_GENERATION,
    TEST_EXECUTION,
    DEPLOYMENT,
    MONITORING,
    DOCUMENTATION,
    COST_ANALYSIS,
    SECURITY_ANALYSIS,
    UX_DESIGN,
    AI_MODEL_DEVELOPMENT
}
