package com.forgeos.memory.domain;

public enum MemoryType {
    FACT,
    DECISION,
    PREFERENCE,
    REQUIREMENT,
    ARCHITECTURE_DECISION,
    TECHNICAL_KNOWLEDGE,
    LESSON_LEARNED,
    INCIDENT,
    BUG_PATTERN,
    CODE_CONVENTION,
    PROJECT_CONVENTION,
    BUSINESS_RULE,
    USER_PREFERENCE,
    WORKFLOW_RESULT,
    AGENT_RESULT,
    TEST_RESULT,
    DEPLOYMENT_RESULT,
    SECURITY_FINDING,
    DOCUMENTATION_KNOWLEDGE
}
