package com.forgeos.tools.domain;

public enum ToolErrorCode {
    TOOL_NOT_FOUND,
    TOOL_DISABLED,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_ARGUMENTS,
    VALIDATION_FAILED,
    SANDBOX_VIOLATION,
    TIMEOUT,
    CANCELLED,
    EXECUTION_FAILED,
    RESOURCE_LIMIT,
    NETWORK_DENIED,
    SECRET_ACCESS_DENIED,
    OUTPUT_VALIDATION_FAILED,
    APPROVAL_REQUIRED,
    APPROVAL_DENIED,
    ENVIRONMENT_NOT_ALLOWED,
    UNKNOWN_ERROR
}
