package com.forgeos.context.domain;

public enum ContextSection {
    IDENTITY,
    SYSTEM_CONSTRAINTS,
    OBJECTIVE,
    TASK,
    REQUIREMENTS,
    ACCEPTANCE_CRITERIA,
    ARCHITECTURE,
    TECHNOLOGY,
    PROJECT_CONVENTIONS,
    RELEVANT_FILES,
    MEMORY,
    PREVIOUS_WORK,
    ARTIFACTS,
    TEST_RESULTS,
    TOOL_RESULTS,
    DECISIONS,
    SECURITY_REQUIREMENTS,
    QUALITY_REQUIREMENTS,
    DEADLINES,
    BUDGET,
    OUTPUT_REQUIREMENTS,
    EVIDENCE
}
