package com.forgeos.organization.domain.security;

public enum Permission {
    ORGANIZATION_READ,
    ORGANIZATION_UPDATE,
    MEMBER_READ,
    MEMBER_INVITE,
    MEMBER_REMOVE,

    PROJECT_CREATE,
    PROJECT_READ,
    PROJECT_UPDATE,
    PROJECT_DELETE,

    WORKSPACE_READ,
    WORKSPACE_WRITE,

    AGENT_READ,
    AGENT_CREATE,
    AGENT_UPDATE,
    AGENT_EXECUTE,

    WORKFLOW_READ,
    WORKFLOW_CREATE,
    WORKFLOW_EXECUTE,

    ARTIFACT_READ,
    ARTIFACT_WRITE,

    APPROVAL_READ,
    APPROVAL_DECIDE,

    AUDIT_READ,
    SECURITY_ADMIN
}
